### ISSUE TITLE
OR WHERE ASSOCIATED

### ISSUE THREAD

**Issue by aiqbalsyah** [sourcefuse/loopback4-sequelize#41] opened 2024-05-04 05:48 UTC
I really confuse for filtering data when i want to make conditions.
My table primary is Events and Inner Join to HomeClubs ands AwaysClubs;

i'm trying to make conditions 

`Where Events.date = 2024-03-04 AND (Homeclubs.name LIKE 'MANCHESTER' OR AwayClub.name LIKE 'MANCHESTER')`

it will be nice if i can know the filter conditions.

**Comment by aiqbalsyah** [comment] 2024-05-04 11:34
![Snap(1)](https://github.com/sourcefuse/loopback4-sequelize/assets/22832751/44f39371-6390-48fb-956f-47296088eddd)
![carbon(1)](https://github.com/sourcefuse/loopback4-sequelize/assets/22832751/d5eb31cb-5c7b-4c94-b65c-ac83ce902faf)

**Comment by yeshamavani** [comment] 2024-05-06 04:45
@aiqbalsyah this particular extension is now officially part of Loopback4 please refer this https://github.com/loopbackio/loopback-next/tree/master/extensions/sequelize

**Comment by basquiatmarley** [comment] 2024-05-06 06:03
@yeshamavani yes i know it and i have to read it. on documentation we could added some where only on spesific include relation or on parent table. where condition not properly generated as right.

**Comment by yeshamavani** [comment] 2024-05-06 06:43
Please refer - https://github.com/loopbackio/loopback-next/tree/master/extensions/sequelize#relations
https://github.com/shubhamp-sf/sequelize-extension-relation-test

**Comment by aiqbalsyah** [comment] 2024-05-06 12:27
@yeshamavani you dont get it what i mean bro
```
{
  "include": [{
      "relation": "todoList",
      "scope": {
        "where": { "color": "black" }
      }
  }]
}
```
TODO.ID - TODO.colorID -  COLOR.TITLE
1 - 2 - RED
2 - 3 - BLUE
3-  4- GREEN
4 - 5 - BLUE

that code only work if todo only black color just one condition.
what if i want to show todo with Todo.id 1 Or Color.title  is BLUE?

**Comment by shubhamp-sf** [comment] 2024-05-06 12:43
Hi @aiqbalsyah, Sorry but your comments here are a little bit vague/tough to make sense of.

I highly recommend  you to provide a minimal reproduction repo containing those models and also a comparison of the output of 
 running same filters with and without using Sequelize extension to understand your issue better.

Also since this repository is not a right place for this. I'm closing this issue here. Please open a new one on [loopback-next](https://github.com/loopbackio/loopback-next/) repository.

**Closed by shubhamp-sf** 2024-05-06 12:43 UTC
